apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickflow-frontend
  labels:
    app: quickflow-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickflow-frontend
  template:
    metadata:
      labels:
        app: quickflow-frontend
    spec:
      containers:
      - name: frontend
        image: quickflow-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: quickflow-frontend
spec:
  selector:
    app: quickflow-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
