spring.application.name=Ai-application
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2
# Use H2 in file mode
spring.datasource.url=jdbc:h2:file:C:/Users/taher/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable automatic table creation
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs (for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
